/** partie 1 **/
/** 1 **/
SPOOL tp1output.log;

CREATE TABLESPACE INTERVENTION_TBS
DATAFILE 'INTERVENTION_TBS1.DAT'
SIZE 100M
AUTOEXTEND ON
ONLINE;

CREATE TEMPORARY TABLESPACE INTERVENTION_tempTBS
TEMPFILE 'INTERVENTION_tempTBS1.DAT'
SIZE 100M
AUTOEXTEND ON;

/** 2 **/
CREATE USER DBAINTERVENTION
IDENTIFIED BY DBAINTERVENTION
DEFAULT TABLESPACE INTERVENTION_TBS
TEMPORARY TABLESPACE INTERVENTION_tempTBS;

/** 3 **/
GRANT ALL PRIVILEGES TO DBAINTERVENTION;

SPOOL OFF;